#!/bin/env bash

calendar(){
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"

    run() {
        eww open calendar
    }

    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi

    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        run
    else
        eww close calendar
        rm "$LOCK_FILE"
    fi
}

if [ "$1" = "calendar" ]; then
    calendar
fi
