[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[mode]
normal_main = { fg = "white", bg = "black" }
normal_alt  = { fg = "black", bg = "white" }
select_main = { fg = "black", bg = "white" }
select_alt  = { fg = "white", bg = "black" }
unset_main  = { fg = "red", bg = "white"  }
unset_alt   = { fg = "white", bg = "red" }

[mgr]
count_copied   = {fg = "yellow", bg = "black"}
count_cut      = {fg = "red", bg = "black"}
count_selected = {fg = "white", bg = "black"}



[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = []
